---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-5.8
  - name: centos-6.5
  - name: centos-7.1
  - name: amazon-2014.09
  - name: amazon-2015.03

suites:
  - name: default
    run_list:
      - recipe[chef_install_configure_collectd::default]
      - recipe[chef_install_configure_collectd::config-collectd]
      - recipe[chef_install_configure_collectd::config-write_http]
    attributes:
